### ISSUE TITLE
vpnc: can't initialise tunnel interface:1

### ISSUE THREAD

**Issue by ndjhartman** [ndpgroup/vpnc#12]
I'm trying to use VPNC on a Raspberry Pi 4. After compiling with Bitbake, and deploying to target I'm unable to make a connection to the VPN.

```sudo vpnc
vpnc: Error binding to source port. Try '--local-port 0'
```

Weird. Running
```
netstat -tulpna | grep 500
```
There is nothing on port 500. Let's try --local-port 0

```
sudo vpnc --local-port 0
vpnc: can't initialise tunnel interface:1
```

The tunnel device exists at /dev/net/tun and has executable permissions. The vpn is connectable via vpnc on other distributions.

**Comment by jflemer-ndp** [comment]
This is a fork only to add specific Juniper support. You could ask the same question in the main vpnc project.
