### ISSUE TITLE
vpnc-script adds incorrect nameserver in /etc/resolv.conf

### ISSUE THREAD

**Issue by sammcj** [ndpgroup/vpnc#3]
When using vpnc-script it incorrectly adds `255.255.255.255` as a DNS server into /etc/resolv.conf
This causes DNS to resolve very slowly or time out.
OS: OSX 10.11

``` bash
~  % cat /etc/resolv.conf
domain fritz.box
nameserver 192.168.0.1

~  % openconnect <vpn server> --juniper -s /etc/vpnc/vpnc-script

~  % cat /etc/resolv.conf
domain fritz.box
nameserver 10.51.20.103
nameserver 255.255.255.255
nameserver 192.168.0.1
```

**Comment by dwmw2** [comment]
Er, but that's openconnect not vpnc. Can you report it to the openconnect-devel@lists.infradead.org mailing list as requested at http://www.infradead.org/openconnect/mail.html please?
