### ISSUE TITLE
Outdated libgnutls and libgcrypt11

### ISSUE THREAD

**Issue by asbjornu** [ndpgroup/vpnc#4]
It would be nice with a more up to date build of vpnc that didn't depend on outdated packages like [libgcrypt11](http://packages.ubuntu.com/trusty-updates/libgcrypt11) and [libgnutls26](http://packages.ubuntu.com/trusty-updates/libgnutls26) which I had to install separately on Ubuntu 15.10.

**Comment by jflemer-ndp** [comment]
Updated to latest upstream release (0.5.3r550-2) for Ubuntu 15.10.
